user: default
home: "/home/{{ user }}"
git_rootrepo: "{{ home }}/git"
network_dns: "8.8.8.8"
network_interface: "{{ ansible_default_ipv4.interface }}"
ssh_port: 22
allowed_ip: "0.0.0.0"

#network_gateway, network_mask
# network_subnet