---
- apt: name=aptitude state=present

- name: "install system updates for debian systems (1/2)"
  apt: update_cache=yes cache_valid_time=3600

- name: "install system updates for debian systems (2/2)"
  apt: upgrade=safe

- name: "Install some system tools..."
  apt:
    pkg:
      - tree
      - curl
      - net-tools
      - refind
      - git
      - firewalld
      - jq
      - units
      - nmap
      - initramfs-tools
      - pip
      - ansible # needed by gnome_extensions module
      - gnupg
      - lsb-release

- name: "Logical evaluation..."
  stat:
    path: "/etc/apt/sources.list.d/docker.list"
  register: f

- name: "Adding Docker Repo key"
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: not f.stat.exists

- name: "Configuring Docker Repo"
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
  when: not f.stat.exists

- name: "Install Docker..."
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify: Restart docker
  when: not f.stat.exists

- name: "Install locate package..."
  apt:
    pkg: locate
  notify: Run updatedb

- name: "Configure Regional language (1/2)"
  community.general.locale_gen:
    name: "{{ locale }}.UTF-8"
    state: present

- name: "Configure Regional language (2/2)"
  command: localectl set-locale LANG={{ locale }}.UTF-8 LC_ALL={{ locale }}.UTF-8

# - name: "Removing some default Applications..."
#   apt:
#     pkg:
#       - blabla
#     state: absent
#     purge: yes

- name: "Remove dependencies that are no longer required"
  apt:
    autoremove: yes
#remove at the end fswatch
#libsodium-dev
