- hosts: all
  gather_facts: true
  collections:
    - jaybeede.linux_server
  tasks:
    # - import_role:
    #     name: packages
    # - import_role:
    #     name: system
    - import_role:
        name: docker
