- hosts: all
  gather_facts: true
  collections:
    - jaybeede.linux_server
  tasks:
    - include_role:
        name: "{{ item }}"
      loop:
        - packages
        - system
    - include_role:
        name: "{{ item }}"
      loop:
        - docker
        - cron
      when: inventory_hostname in groups["web"]
    - include_role:
        name: docker_wireguard
      when: inventory_hostname in groups["vpn"]