---
galaxy_info:
  author: JayBee <jb.social@outlook.com>
  description: Packages for linux server
  license: GPL-3.0-or-later
  galaxy_tags:
  - "linux"
  - "debian"
  - "server"
  - "packages"
  - "apt"
  - "language"
  - "regional"
  - "repo"
  platforms:
    - name: Debian
      versions:
        - any
