---
namespace: jaybeede
name: linux_desktop
version: 2.0.3
readme: README.md
authors:
  - JayBee <jb.social@outlook.com>
description: your collection description
license:
  - GPL-3.0-or-later
tags:
  - "linux"
  - "desktop"
  - "apt"
  - "chromium"
  - "dashtopanel"
  - "freedesktop"
  - "gnomebookmarks"
  - "gnomeextensions"
  - "gnomenotifications"
  - "keepassxc"
  - "keyboardshortcuts"
  - "libreoffice"
  - "nemo"
  - "onedrive"
  - "printer"
  - "snap"
  - "systemd"
  - "vlc"
  - "vscode"
  - "wallpaper"
repository: https://github.com/JayBeeDe/ansible_collections
documentation: https://github.com/JayBeeDe/ansible_collections/blob/main/jaybeede/linux_desktop/README.md
homepage: https://jean-baptiste-delon.com/
issues: https://github.com/JayBeeDe/ansible_Linux-Desktop/issues
build_ignore:
  - '*/__pycache__/*'
  - '*.log'
  - '*.old'
  - '*/files/Bookmarks'
  - '*/group_vars/all.yml'
  - '*/vault-tmp'
