---
namespace: jaybeede
name: linux_desktop
version: 0.0.1
readme: README.md
authors:
  - JayBee <jb.social@outlook.com>
description: your collection description
license:
  - GPL-3.0-or-later
license_file: "./LICENSE"
tags:
  - "linux"
  - "ubuntu"
  - "desktop"
  - "freedesktop.org"
repository: https://github.com/JayBeeDe/ansible_collections
documentation: https://github.com/JayBeeDe/ansible_collections/blob/master/docs/README.md
homepage: https://jean-baptiste-delon.com/
issues: https://github.com/JayBeeDe/ansible_Linux-Desktop/issues
build_ignore:
  - "python3-gi"
  - "python3-gi-cairo"
  - "gir1.2-gtk-3.0"
