---
- name: "Update grub"
  command: update-grub

- name: "Restart firewalld"
  systemd:
    name: "firewalld"
    state: restarted
    enabled: yes
  become: yes
  become_user: root

- name: "Restart libvirtd"
  systemd:
    name: "libvirtd"
    state: restarted
    enabled: yes
  become: yes
  become_user: root

- name: "Restart sshd"
  systemd:
    name: "ssh"
    state: restarted
    enabled: yes
  become: yes
  become_user: root

- name: "Fix broken packages"
  shell: apt --fix-broken -y install
  become: yes
  become_user: root