---

- block:
    - name: "Configuring MotionBox desktop shortcut..."
      desktop_launchers:
        freedesktop_Name: "MotionBox"
        freedesktop_Icon: "{{ home }}/.local/share/icons/motionbox.png"
        target: 'bash -c "export LD_LIBRARY_PATH=/opt/MotionBox; export QT_PLUGIN_PATH=/opt/MotionBox; /opt/MotionBox/MotionBox"'
        location: "/usr/share/applications/MotionBox.desktop"
  become: yes
  become_user: "root"
- block:
    - name: "Configuring arc-menu shortcuts..."
      dconf: key="/org/gnome/shell/extensions/arcmenu/pinned-app-list" value="['Navigateur Web Google Chrome', 'google-chrome', 'google-chrome.desktop', 'Fichiers', 'folder', 'nemo.desktop', 'Visual Studio Code', '', 'code.desktop', 'VLC media player', 'vlc', 'vlc.desktop', 'Windows', '{{ home }}/.local/share/icons/windows.png', 'connectWindows.desktop', 'Krita', '', 'org.kde.krita.desktop', 'draw.io', '', 'drawio_drawio.desktop', 'P3X OneNote', '', 'p3x-onenote_p3x-onenote.desktop', 'Skype', '', 'skype_skypeforlinux.desktop', 'Numériseur de documents', 'org.gnome.SimpleScan', 'simple-scan.desktop', 'MotionBox', '{{ home }}/.local/share/icons/motionbox.png', 'MotionBox.desktop', 'EasyEffects', 'EasyEffects', '', 'com.github.wwmm.easyeffects.desktop']"

    - name: "Configuring gnome bookmarks..."
      dconf: key="/org/gnome/shell/favorite-apps" value="['google-chrome.desktop', 'nemo.desktop', 'code.desktop', 'vlc.desktop', 'connectWindows.desktop', 'org.kde.krita.desktop', 'drawio_drawio.desktop', 'p3x-onenote_p3x-onenote.desktop', 'skype_skypeforlinux.desktop', 'simple-scan.desktop', 'MotionBox.desktop', 'com.github.wwmm.easyeffects.desktop']"
    - name: "Configuring evolution desktop shortcut..."
      desktop_launchers:
        source: "/usr/share/applications/org.gnome.Evolution.desktop"
        target: 'bash -c ''for item in $(ps aux | grep evolution | grep -v grep | sed -r "s:^(\\S+\\s+)(\\S+)(.*)$:\\2:g"); do kill -9 $item; done; sleep 10; evolution 2>/dev/null & pid=$!; sleep 5; for item in $(xdotool search --pid $pid); do xdotool windowminimize $item; done'''
        location: "$DIRECTORY_DESKTOP/evolution.desktop"
      # register: testout
    # - name: dump test output
    #   debug:
    #     msg: "{{ testout }}"
    - name: "Configuring telegram desktop shortcut..."
      desktop_launchers:
        source: "/usr/share/applications/telegramdesktop.desktop"
        target: 'bash -c ''for item in $(ps aux | grep telegram-desktop | grep -v grep | sed -r "s:^(\\S+\\s+)(\\S+)(.*)$:\\2:g"); do kill -9 $item; done; sleep 5; telegram-desktop 2>/dev/null & pid=$!; sleep 5; for item in $(xdotool search --pid $pid); do xdotool windowminimize $item; done'''
        location: "$DIRECTORY_DESKTOP/telegram.desktop"
    - name: "Configuring keepassxc desktop shortcut..."
      desktop_launchers:
        source: "/usr/share/applications/org.keepassxc.KeePassXC.desktop"
        target: 'bash -c ''for item in $(ps aux | grep keepassx | grep -v grep | sed -r "s:^(\\S+\\s+)(\\S+)(.*)$:\\2:g"); do kill -9 $item; done; sleep 5; keepassxc "{{ kdbx_path }}" --keyfile "{{ key_path }}" 2>/dev/null & pid=$!; sleep 5; for item in $(xdotool search --pid $pid); do xdotool windowminimize $item; done & disown;'''
        location: "$DIRECTORY_DESKTOP/keepassxc.desktop"
    - name: "Configuring connectWindows 1 desktop shortcut..."
      desktop_launchers:
        freedesktop_Name: "Windows"
        freedesktop_Comment: "Connect to Ms Windows"
        freedesktop_Icon: "{{ home }}/.local/share/icons/windows.png"
        freedesktop_Categories: "Utility"
        target: 'bash -c "{{ home }}/.local/share/scripts/connectWindows.sh {{ home }}/.local/share/remmina/group_rdp_{{ rdp_name }}_{{ rdp_host }}-{{ rdp_port }}.remmina"'
        location: "$HOME/.local/share/applications/connectWindows.desktop"
    - name: "Configuring connectWindows 2 desktop shortcut..."
      desktop_launchers:
        freedesktop_Name: "Windows"
        freedesktop_Comment: "Connect to Ms Windows"
        freedesktop_Icon: "{{ home }}/.local/share/icons/windows.png"
        freedesktop_Categories: "Utility"
        target: 'bash -c "{{ home }}/.local/share/scripts/connectWindows.sh .local/share/remmina/group_rdp_{{ rdp_name }}_{{ rdp_host }}-{{ rdp_port }}.remmina"'
        location: "$DIRECTORY_DESKTOP/connectWindows.desktop"
    - name: "Configuring conky autostart shortcut..."
      desktop_launchers:
        freedesktop_Name: "Conky"
        target: 'sh -c "conky --config=$HOME/.conky/default/default.conf --alignment=top_left -x 1300 --daemonize 2>&1 >/dev/null"'
        location: "$HOME/.config/autostart/conky.desktop"
    - name: "Configuring evolution autostart shortcut..."
      desktop_launchers:
        freedesktop_Name: "Evolution"
        target: 'bash -c "sleep 10; evolution 2>/dev/null & pid=$!; sleep 5; for item in $(xdotool search --pid $pid); do xdotool windowminimize $item; done"'
        location: "$HOME/.config/autostart/evolution.desktop"
    - name: "Configuring telegram autostart shortcut..."
      desktop_launchers:
        freedesktop_Name: "Telegram"
        target: 'bash -c "sleep 5; telegram-desktop 2>/dev/null & pid=$!; sleep 5; for item in $(xdotool search --pid $pid); do xdotool windowminimize $item; done"'
        location: "$HOME/.config/autostart/telegram.desktop"
    - name: "Configuring keepassxc autostart shortcut..."
      desktop_launchers:
        freedesktop_Name: "KeepassXC"
        target: 'bash -c "sleep 5; keepassxc "{{ kdbx_path }}" --keyfile "{{ key_path }}" 2>/dev/null & pid=$!; sleep 5; for item in $(xdotool search --pid $pid); do xdotool windowminimize $item; done & disown;"'
        location: "$HOME/.config/autostart/keepassxc.desktop"
    - name: "Configuring nemo autostart shortcut..."
      desktop_launchers:
        source: "/usr/share/applications/nemo-autostart.desktop"
        target: "nemo-desktop"
        location: "$HOME/.config/autostart/nemo-autostart.desktop"
  become: yes
  become_user: "{{ user }}"
