---
- block:
    - name: Set a hostname (1/2)
      ansible.builtin.hostname:
        name: "{{ ansible_host }}"

    - name: Set a hostname (2/2)
      lineinfile:
        dest: "/etc/hosts"
        regexp: "^127.0.1.1\t+.+$"
        line: "127.0.1.1\t{{ ansible_host }}"
        state: present
        backup: no

    - name: "Configuring system network..."
      nmcli:
        type: ethernet
        conn_name: "net-{{ network_interface }}"
        ifname: "{{ network_interface }}"
        dns4:
          - "{{ network_dns }}"
        autoconnect: yes
        state: present

    - name: "Configuring sshd (1/8)..."
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?Port [0-9]+$"
        replace: "Port {{ ssh_port }}"
        backup: no
      notify: Restart sshd

    - name: "Configuring sshd (2/8)..."
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?UseDNS .+$"
        replace: "UseDNS no"
        backup: no
      notify: Restart sshd

    - name: "Configuring sshd (3/8)..."
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin .+$"
        replace: "PermitRootLogin prohibit-password"
        backup: no
      notify: Restart sshd

    - name: "Configuring sshd (4/8)..."
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitEmptyPasswords .+$"
        replace: "PermitEmptyPasswords no"
        backup: no
      notify: Restart sshd

    - name: "Configuring sshd (5/8)..."
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication .+$"
        replace: "PasswordAuthentication no"
        backup: no
      notify: Restart sshd

    - name: "Configuring sshd (6/8)..."
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?UsePAM .+$"
        replace: "UsePAM no"
        backup: no
      notify: Restart sshd

    - name: "Configuring sshd (7/8)..."
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?PrintMotd .+$"
        replace: "PrintMotd yes"
        backup: no
      notify: Restart sshd

    - name: "Configuring sshd (8/8)..."
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^AllowUsers {{ user }}@{{ allowed_ip }} root@localhost root@127.0.0.1 {{ user }}@127.0.0.1 {{ user }}@localhost {{ user }}@172.18.* {{ user }}@172.17.*"
        line: "AllowUsers {{ user }}@{{ allowed_ip }} root@localhost root@127.0.0.1 {{ user }}@127.0.0.1 {{ user }}@localhost {{ user }}@172.18.* {{ user }}@172.17.*"
        backup: no
      notify: Restart sshd

    - name: "Configuring firewalld (1/3)..."
      copy:
        src: "{{ role_path }}/files/firewalld.xml"
        dest: /etc/firewalld/zones/public.xml
        mode: "0644"
        owner: "root"
        group: "root"
        force: no
      notify: Restart firewalld

    - name: "Configuring firewalld (2/3)..."
      replace:
        path: /etc/firewalld/zones/public.xml
        regexp: "allowed-ip-ansible-template"
        replace: "{{ allowed_ip }}/32"
        backup: no
      notify: Restart firewalld

    - name: "Configuring firewalld (3/3)..."
      replace:
        path: /etc/firewalld/zones/public.xml
        regexp: "ssh-port-ansible-template"
        replace: "{{ ssh_port | string }}"
        backup: no
      notify: Restart firewalld

    - name: "Masking ctrl-alt-del.target..."
      systemd:
        name: "ctrl-alt-del.target"
        enabled: no
        masked: yes
        daemon_reload: yes

    - name: "Configuring motd..."
      copy:
        src: "{{ role_path }}/files/motd"
        dest: /etc/motd
        mode: "0755"
        owner: "root"
        group: "root"

    - name: "Configuring aliases for root user (1/2)..."
      copy:
        src: "{{ role_path }}/files/bash_aliases"
        dest: /root/.bash_aliases
        mode: "0755"
        owner: "root"
        group: "root"
        force: no

    - name: "Configuring aliases for root user (2/2)..."
      lineinfile:
        path: /root/.bashrc
        state: present
        regexp: ^(\s*)(.|source)( ~/.bash_aliases)(\s*)$
        line: ". ~/.bash_aliases"
        backup: no

    - name: "Overriding env variables to {{ user }} for root user (1/3)..."
      replace:
        path: /root/.bash_aliases
        regexp: '\$VPJP'
        replace: "{{ git_rootrepo }}/"
        backup: no
      changed_when: false

    - name: "Overriding env variables to {{ user }} for root user (2/3)..."
      replace:
        path: /root/.bash_aliases
        regexp: '\$HOME'
        replace: "{{ home }}/"
        backup: no
      changed_when: false

    - name: "Overriding env variables to {{ user }} for root user (3/3)..."
      replace:
        path: /root/.bash_aliases
        regexp: '\$USER'
        replace: "{{ user }}"
        backup: no
      changed_when: false

  become: yes
  become_user: "root"
  environment:
    PWD: ""
- block:
    - name: "Configuring aliases for {{ user }} user (1/2)..."
      copy:
        src: "{{ role_path }}/files/bash_aliases"
        dest: "{{ home }}/.bash_aliases"
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"
        force: no

    - name: "Configuring aliases for {{ user }} user (2/2)..."
      lineinfile:
        path: "{{ home }}/.bashrc"
        state: present
        regexp: ^(\s*)(.|source)( ~/.bash_aliases)(\s*)$
        line: ". ~/.bash_aliases"
        backup: no

    - name: "Overriding env variables to {{ user }} for {{ user }} user..."
      replace:
        path: "{{ home }}/.bash_aliases"
        regexp: '\$VPJP'
        replace: "{{ git_rootrepo }}/"
        backup: no
      changed_when: false

  become: yes
  become_user: "{{ user }}"
  environment:
    PWD: ""
