---
- block:
    - name: "Logical evaluation..."
      stat:
        path: "/etc/apt/sources.list.d/vscode.list"
      register: f

    - name: "Adding Microsoft Repo key"
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      when: not f.stat.exists

    - name: "Configuring Microsoft Repo"
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      when: not f.stat.exists

    - name: "Fixing Microsoft Repo..."
      command: mv "/etc/apt/sources.list.d/packages_microsoft_com_repos_vscode.list" "/etc/apt/sources.list.d/vscode.list"
      when: not f.stat.exists

    - name: "Logical evaluation..."
      stat:
        path: "/etc/apt/sources.list.d/google-chrome.list"
      register: f2

    - name: "Adding Google Repo key"
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present
      when: not f2.stat.exists

    - name: "Configuring Google Repo"
      apt_repository:
        repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
      when: not f2.stat.exists

    - name: "Fixing Google Repo..."
      command: mv "/etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list" "/etc/apt/sources.list.d/google-chrome.list"
      when: not f2.stat.exists

    - name: "Logical evaluation..."
      stat:
        path: "/etc/apt/sources.list.d/onedrive.list"
      register: f3

    - name: "Adding onedrive Repo key"
      apt_key:
        url: https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_22.04/Release.key
        state: present
      when: not f3.stat.exists

    - name: "Configuring onedrive Repo"
      apt_repository:
        repo: deb https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_22.04/ ./
      when: not f3.stat.exists

    - name: "Fixing onedrive Repo..."
      command: mv "/etc/apt/sources.list.d/download_opensuse_org_repositories_home_npreining_debian_ubuntu_onedrive_xUbuntu_22_04.list" "/etc/apt/sources.list.d/onedrive.list"
      when: not f3.stat.exists

    - name: "install system updates for ubuntu systems"
      apt:
        upgrade: safe
        cache_valid_time: 3600

    - name: "Install some system tools..."
      apt:
        pkg:
          - sshpass
          - tree
          - curl
          - net-tools
          - gnome-shell-extensions
          - gnome-tweak-tool
          - dconf-editor
          - terminator
          - refind
          - qemu-kvm
          - qemu
          - virt-manager
          - virtinst
          - qemu-guest-agent
          - remmina
          - bridge-utils
          - cpu-checker
          - qemu-utils
          - git
          - qt5ct
          - qt5-style-plugins
          - firewalld
          - jq
          - network-manager
          - xdotool
          - ccze
          - libnm-dev
          - python3-gi
          - pylint
          - ntfs-3g
          - imagemagick
          - units
          - nmap
          - gparted
          - libperl-critic-perl
          - perltidy
          - id3v2
          - initramfs-tools
          - timeshift
          - lua5.4
          - pip
          - acpitool
          - kdocker
          - shellcheck
          - shfmt
          - ansible # needed by gnome_extensions module
          - gettext # needed by arc-menu gnome extension
          - gir1.2-gmenu-3.0 # needed by arc-menu gnome extension
          - gnome-menus # needed by arc-menu gnome extension
          - libgettextpo-dev # needed by arc-menu gnome extension
          - libglib2.0-bin # needed by arc-menu gnome extension

    - name: "Install locate package..."
      apt:
        pkg: locate
      notify: Run updatedb

    - name: "Install Desktop Applications (1/3)..."
      apt:
        pkg:
          - vlc
          - libreoffice-gtk
          - libreoffice
          - google-chrome-stable
          - code
          - krita
          - flameshot
          - p7zip-full
          - evolution
          - evolution-ews
          - nemo
          - keepassxc
          - xsel
          - telegram-desktop
          - conky
          - openssh-server
          - gpick
          - audacity
          - soundconverter
          - handbrake
          - gnome-shell-extension-gsconnect
          - gnome-shell-extension-gsconnect-browsers
          # - gir1.2-ebook
          # - gir1.2-ebookcontacts
          # - gir1.2-edataserver

    # - name: "Install motionbox related packages..."
    #   apt:
    #     pkg:
    #     - libtorrent-dev
    #     - libboost-all-dev
    #     - libdvd-pkg to check interactifve !!!!!! dpkg-reconfigure libdvd-pkg interactive too
    #     - ubuntu-restricted-extras interactifve

    - name: "Install Desktop Applications (2/3)..."
      snap:
        name:
          - p3x-onenote
          - drawio

    - name: "Install Desktop Applications (3/3)..."
      snap:
        name:
          - skype
          - dmd
        classic: yes

    #snap shfmt
    #for shell formatter extension ?

    - name: "Install onedrive related packages..."
      apt:
        pkg:
          - build-essential
          - libcurl4-openssl-dev
          - libsqlite3-dev
          - libnotify-dev
          - onedrive

    - name: "Install Regional Packages..."
      apt:
        pkg:
          - "hunspell-{{ language }}"
          - "hunspell-{{ language }}-revised"
          - "libreoffice-l10n-{{ language }}"
          - "hyphen-{{ language }}"
          - "mythes-{{ language }}"

    - name: "Removing some default Desktop Applications..."
      apt:
        pkg:
          - aisleriot
          - brasero
          - cheese
          - com.github.donadigo.eddy
          - firefox
          - foot
          - geary
          - gnome-calendar
          - gnome-initial-setup
          - gnome-mahjongg
          - gnome-mines
          - gnome-sudoku
          - gnome-todo
          - mpv
          - rhythmbox
          - soundconverter
          - thunderbird
          - totem
          - transmission-gtk
          - virt-viewer
        state: absent
        purge: yes

    - name: "Remove dependencies that are no longer required"
      apt:
        autoremove: yes
  #remove at the end fswatch
  #libsodium-dev

  become: yes
  become_user: "root"
