---
- block:
    - name: "Logical evaluation..."
      stat:
        path: "/etc/apt/sources.list.d/vscode.list"
      register: f

    - name: "Adding Microsoft Repo key"
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      when: not f.stat.exists

    - name: "Configuring Microsoft Repo"
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      when: not f.stat.exists

    - name: "Fixing Microsoft Repo..."
      command: mv "/etc/apt/sources.list.d/packages_microsoft_com_repos_vscode.list" "/etc/apt/sources.list.d/vscode.list"
      when: not f.stat.exists

    # - name: "install system updates for ubuntu systems"
    #   apt:
    #     upgrade: safe
    #     cache_valid_time: 3600

    - name: "Install some system tools..."
      apt:
        pkg:
          - sshpass
          - tree
          - curl
          - dunst
          - net-tools
          - gnome-shell-extensions
          - gnome-tweak-tool
          - dconf-editor
          - terminator
          - refind
          - qemu-kvm
          - qemu
          - virt-manager
          - virtinst
          - qemu-guest-agent
          - remmina
          - bridge-utils
          - cpu-checker
          - qemu-utils
          - git
          - qt5ct
          - qt5-style-plugins
          - firewalld
          - jq
          - network-manager
          - xdotool
          - ccze
          - libnm-dev
          - python3-gi
          - pylint
          - ntfs-3g
          - imagemagick
          - units
          - nmap
          - gparted
          - libperl-critic-perl
          - perltidy
          - id3v2
          - initramfs-tools
          - timeshift
          - lua5.4
          - lua-json
          - lua-socket
          - pip
          - acpitool
          - kdocker
          - shellcheck
          - shfmt
          - ansible # needed by gnome_extensions module
          - gettext # needed by arc-menu gnome extension
          - gir1.2-gmenu-3.0 # needed by arc-menu gnome extension
          - gnome-menus # needed by arc-menu gnome extension
          - libgettextpo-dev # needed by arc-menu gnome extension
          - libglib2.0-bin # needed by arc-menu gnome extension
          - flatpak # needed by flatpak module
          - libfuse2 # needed by pCloudDrive

    - name: "Install locate package..."
      apt:
        pkg: locate
      notify: Run updatedb

    - name: "Install Desktop Applications (1/3)..."
      apt:
        pkg:
          - element-desktop
          - firefox
          - vlc
          - libreoffice-gtk
          - libreoffice
          - code
          - krita
          - flameshot
          - p7zip-full
          - nemo
          - keepassxc
          - xsel
          - conky
          - openssh-server
          - audacity
          - soundconverter
          - handbrake
          - gnome-shell-extension-gsconnect
          - gnome-shell-extension-gsconnect-browsers
          # - gir1.2-ebook
          # - gir1.2-ebookcontacts
          # - gir1.2-edataserver

    - name: "Install motionbox related packages..."
      apt:
        pkg:
          - libtorrent-dev
          - libdvd-pkg
          - ubuntu-restricted-extras

    - name: "Install Desktop Applications (2/3)..."
      flatpak:
        name:
          - flathub
          - com.github.tchx84.Flatseal
          - com.github.wwmm.easyeffects
          - net.cozic.joplin_desktop
          - org.gnome.Evolution
          - "org.gtk.Gtk3theme.{{ theme_primary_name }}"
          - org.pipewire.Helvum

    - name: "Install Desktop Applications (3/3)..."
      snap:
        name:
          - drawio

    - name: "Install Desktop Applications (3/3)..."
      snap:
        name:
          - dmd
        classic: yes

    - name: "Install Regional Packages..."
      apt:
        pkg:
          - "hunspell-{{ language }}"
          - "hunspell-{{ language }}-revised"
          - "libreoffice-l10n-{{ language }}"
          - "hyphen-{{ language }}"
          - "mythes-{{ language }}"

    - name: Installing pCloudDrive (1/3)...
      file:
        path: /opt/pCloud/
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Logical evaluation..."
      stat:
        path: /opt/pCloud/pCloudDrive
      register: f

    - name: Installing pCloudDrive (2/3)...
      ansible.builtin.get_url:
        url: https://p-lux4.pcloud.com/cBZPneaGcZx94ojD7ZZZdjixVkZ2ZZHK0ZkZyQbxVZIpZfYZpQZnQZkHZ28ZRzZ6HZUQZhQZ2YZRLZo4ZqFZevXB5ZNoKXnGzYT5Xjjz9firCfufPgpQO7/pcloud
        dest: /opt/pCloud/pCloudDrive
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 777
      when: not f.stat.exists

    - name: Setting correct permissions to /opt/pCloud/pCloudDrive (3/3)...
      file:
        path: /opt/pCloud
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes
      when: not f.stat.exists

    - name: "Logical evaluation..."
      stat:
        path: /opt/MotionBox/MotionBox
      register: f

    - name: Installing MotionBox (1/5)...
      ansible.builtin.get_url:
        url: https://s3-eu-west-1.amazonaws.com/omega.gg/get/MotionBox/MotionBox-2.0.0-4-linux64.tar.gz
        dest: /tmp/MotionBox-2.0.0-4-linux64.tar.gz
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 777
      when: not f.stat.exists

    - name: Extracting MotionBox (2/5)...
      ansible.builtin.unarchive:
        src: /tmp/MotionBox-2.0.0-4-linux64.tar.gz
        dest: /opt
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 775
      when: not f.stat.exists

    - name: "Setting correct permissions to /opt/MotionBox (3/5)..."
      file:
        path: "/opt/MotionBox-2.0.0-4"
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes
      when: not f.stat.exists

    - name: Preparing MotionBox (4/5)...
      ansible.builtin.file:
        dest: /opt/MotionBox
        src: /opt/MotionBox-2.0.0-4
        state: link
      when: not f.stat.exists

    - name: Removing MotionBox artefacts (5/5)...
      ansible.builtin.file:
        path: /tmp/MotionBox-2.0.0-4-linux64.tar.gz
        state: absent
      when: not f.stat.exists

    - name: "Removing some default Desktop Applications..."
      apt:
        pkg:
          - aisleriot
          - brasero
          - cheese
          - com.github.donadigo.eddy
          - firefox
          - foot
          - geary
          - gnome-calendar
          - gnome-initial-setup
          - gnome-mahjongg
          - gnome-mines
          - gnome-sudoku
          - gnome-todo
          - mpv
          - rhythmbox
          - soundconverter
          - thunderbird
          - totem
          - transmission-gtk
          - virt-viewer
        state: absent
        purge: yes

    - name: "Remove dependencies that are no longer required"
      apt:
        autoremove: yes
  #remove at the end fswatch
  #libsodium-dev

  become: yes
  become_user: "root"
