- name: Restart wireguard container
  docker_container:
    name: wireguard-proxy
    restart: true
    state: started
  become: yes

- name: Add routes
  command: bash -c '/etc/network/routes.d/wireguard-down; /etc/network/routes.d/wireguard-up'
  become: yes
