---
- block:
    - name: "Setting correct permissions to {{ home }}/Documents/..."
      file:
        path: "{{ home }}/Documents/"
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes

    - name: "Setting correct permissions to /var/log/..."
      file:
        path: "/var/log/"
        mode: "0777"
      changed_when: false

    - name: Configuring Firefox...
      file:
        path: /etc/firefox/policies/
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Configuring Firefox - Policies...
      copy:
        src: "{{ role_path }}/files/firefox.json"
        dest: /etc/firefox/policies/policies.json
        mode: "0644"
        owner: root
        group: root

  become: yes
  become_user: "root"
- block:
    - name: "Configuring KeepassXC (1/2)..."
      file:
        path: "{{ home }}/.config/keepassxc/"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring KeepassXC (2/2)..."
      copy:
        src: "{{ role_path }}/files/keepassxc.ini"
        dest: "{{ home }}/.config/keepassxc/keepassxc.ini"
        mode: "0664"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring VLC (1/3)..."
      file:
        path: "{{ home }}/.config/vlc/"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring VLC (2/3)..."
      template:
        src: "{{ role_path }}/files/vlc.ini.tpl"
        dest: "{{ home }}/.config/vlc/vlc-qt-interface.conf"
        mode: "0664"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring VLC (3/3)..."
      copy:
        src: "{{ role_path }}/files/vlc-2"
        dest: "{{ home }}/.config/vlc/vlcrc"
        mode: "0600"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring conky (1/5)..."
      file:
        path: "{{ home }}/.config/conky/"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Setting Conky (2/5)..."
      git:
        repo: "https://github.com/JayBeeDe/conky-scripts.git"
        dest: "{{ home }}/.config/conky/JayBeeDe"

    - name: "Setting Conky (3/5)..."
      file:
        src: "{{ home }}/.config/conky/JayBeeDe"
        dest: "{{ home }}/.config/conky/default"
        state: link

    - name: "Setting Conky (4/5)..."
      file:
        path: "{{ home }}/.local/share/fonts/"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Setting Conky (5/5)..."
      copy:
        src: "{{ role_path }}/files/GE-Inspira-Bold.ttf"
        dest: "{{ home }}/.local/share/fonts/GE-Inspira-Bold.ttf"
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring flameshot (1/2)..."
      file:
        path: "{{ home }}/.config/flameshot/"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring flameshot (2/2)..."
      template:
        src: "{{ role_path }}/files/flameshot.ini.tpl"
        dest: "{{ home }}/.config/flameshot/flameshot.ini"
        mode: "0644"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring vscode (1/5)..."
      file:
        path: "{{ home }}/.config/Code/User/"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring vscode (2/5)..."
      template:
        src: "{{ role_path }}/files/vscode.json.tpl"
        dest: "{{ home }}/.config/Code/User/settings.json"
        mode: "0644"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring vscode (3/5)..."
      copy:
        src: "{{ role_path }}/files/vscode-2.json"
        dest: "{{ home }}/.config/Code/User/keybindings.json"
        mode: "0644"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring vscode (4/5)..."
      copy:
        src: "{{ role_path }}/files/vscode-3.json"
        dest: "{{ home }}/.config/Code/User/tasks.json"
        mode: "0644"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring vscode - Installing extensions (5/5)..."
      command: code --install-extension "{{ item }}"
      loop:
        - adpyke.vscode-sql-formatter
        - aeschli.vscode-css-formatter
        - alefragnani.project-manager
        - bibhasdn.unique-lines
        - codezombiech.gitignore
        - DavidAnson.vscode-markdownlint
        - dhoeric.ansible-vault
        - EditorConfig.EditorConfig
        - emilast.LogFileHighlighter
        - exiasr.hadolint
        - foxundermoon.shell-format
        - gamunu.vscode-yarn
        - geeebe.duplicate
        - golang.go
        - hediet.vscode-drawio
        - hogashi.crontab-syntax-highlight
        - JayBeeDe.custom-accentuation-color-dark-high-contrast
        - jq-syntax-highlighting.jq-syntax-highlighting
        - junstyle.php-cs-fixer
        - lkrms.inifmt
        - mhutchie.git-graph
        - mkhl.shfmt
        - ms-azuretools.vscode-docker
        - ms-python.python
        - ms-toolsai.jupyter
        - ms-toolsai.jupyter-keymap
        - ms-toolsai.jupyter-renderers
        - ms-vscode.cmake-tools
        - ms-vscode.cpptools
        - nico-castell.linux-desktop-file
        - redhat.ansible
        - redhat.vscode-commons
        - redhat.vscode-xml
        - redhat.vscode-yaml
        - streetsidesoftware.code-spell-checker
        - streetsidesoftware.code-spell-checker-french
        - timonwong.shellcheck
        - wingrunr21.vscode-ruby
        - yinfei.luahelper
        - zhiyuan-lin.simple-perl
        - ziyasal.vscode-open-in-github
      register: ext
      changed_when: "'already installed' not in ext.stdout"

    - name: "Configuring perlcritic (for vscode extension)..."
      copy:
        src: "{{ role_path }}/files/perlcritic"
        dest: "{{ home }}/.perlcriticrc"
        mode: "0644"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring terminator (1/2)..."
      file:
        path: "{{ home }}/.config/terminator/"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring terminator (2/2)..."
      template:
        src: "{{ role_path }}/files/terminator.ini.tpl"
        dest: "{{ home }}/.config/terminator/config"
        mode: "0644"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring remmina (1/9)..."
      file:
        path: "{{ home }}/.config/remmina/"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring remmina (2/9)..."
      copy:
        src: "{{ role_path }}/files/remmina.ini"
        dest: "{{ home }}/.config/remmina/remmina.pref"
        mode: "0664"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring remmina (3/9)..."
      file:
        path: "{{ home }}/.local/share/remmina/"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring remmina (4/9)..."
      copy:
        src: "{{ role_path }}/files/remmina-2.ini"
        dest: "{{ home }}/.local/share/remmina/group_rdp_{{ rdp_name }}_{{ rdp_host }}-{{ rdp_port }}.remmina"
        mode: "0664"
        owner: "{{ user }}"
        group: "{{ user }}"
        force: no

    - name: "Configuring remmina (5/9)..."
      lineinfile:
        path: "{{ home }}/.local/share/remmina/group_rdp_{{ rdp_name }}_{{ rdp_host }}-{{ rdp_port }}.remmina"
        state: present
        regexp: "^name=.*$"
        line: "name={{ rdp_name }}"
        backup: no

    - name: "Configuring remmina (6/9)..."
      lineinfile:
        path: "{{ home }}/.local/share/remmina/group_rdp_{{ rdp_name }}_{{ rdp_host }}-{{ rdp_port }}.remmina"
        state: present
        regexp: "^server=.*$"
        line: "server={{ rdp_name }}:{{ rdp_port }}"
        backup: no

    - name: "Configuring remmina (7/9)..."
      lineinfile:
        path: "{{ home }}/.local/share/remmina/group_rdp_{{ rdp_name }}_{{ rdp_host }}-{{ rdp_port }}.remmina"
        state: present
        regexp: "^username=.*$"
        line: "username={{ rdp_user }}"
        backup: no

    - name: "Configuring remmina (8/9)..."
      lineinfile:
        path: "{{ home }}/.local/share/remmina/group_rdp_{{ rdp_name }}_{{ rdp_host }}-{{ rdp_port }}.remmina"
        state: present
        regexp: "^sharefolder=.*$"
        line: "sharefolder={{ rdp_sharefolder }}"
        backup: no

    - name: "Configuring remmina (9/9)..."
      file:
        path: "{{ home }}/.local/share/icons/"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring user scripts (1/2)..."
      file:
        path: "{{ home }}/.local/share/scripts/"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring user scripts (2/2)..."
      copy:
        src: "{{ role_path }}/files/connectWindows.sh"
        dest: "{{ home }}/.local/share/scripts/connectWindows.sh"
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"
        force: no

    - name: "Configuring nemo (1/2)..."
      command: xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
      changed_when: false

    # - name: "Configuring nemo (2/2)..."
    #   dconf: key="/org/gnome/desktop/background/show-desktop-icons" value="false"

    - name: "Configuring libreoffice templates (1/2)..."
      file:
        path: "{{ home }}/Templates/"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Configuring libreoffice templates (2/2)..."
      copy:
        src: "{{ role_path }}/files/Default.ott"
        dest: "{{ home }}/Templates/Default.ott"
        mode: "0664"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Setting up git identity (1/2)..."
      git_config:
        name: user.email
        scope: global
        value: "{{ git_email }}"

    - name: "Setting up git identity (2/2)..."
      git_config:
        name: user.name
        scope: global
        value: "{{ git_name }}"

  become: yes
  become_user: "{{ user }}"
