---
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes
  become_user: root
- name: Restart nfs server
  systemd:
    name: nfs-kernel-server
    state: restarted
  become: yes
  become_user: root
- name: Restart wireguard client
  systemd:
    name: wireguard-client
    state: restarted
    daemon_reload: yes
  become: yes
  become_user: root