---
- block:
    # - name: "Configuring system network (1/2)..."
    #   shell: nmcli con delete "net-{{ network_interface }}" || true
    #   changed_when: false

    - name: "Configuring system network (2/2)..."
      nmcli:
        type: ethernet
        conn_name: "net-{{ network_interface }}"
        ifname: "{{ network_interface }}"
        ip4: "{{ network_ip }}/{{ network_subnet | ipaddr('prefix') }}"
        gw4: "{{ network_subnet | ipaddr('1') | ipaddr('ip') }}"

        dns4:
          - "{{ network_dns }}"
        autoconnect: yes
        state:
          present
          #####NOTE that library may need to be patched here
          #####/usr/lib/python3/dist-packages/ansible/modules/net_tools/nmcli.py line 567
          ############FROM
          #####try:
          ##### import gi
          ##### gi.require_version('NMClient', '1.0')
          ##### gi.require_version('NetworkManager', '1.0')
          ##### from gi.repository import NetworkManager, NMClient
          ############REPLACE BY
          ##### try:
          ##### import gi
          ##### gi.require_version('NM', '1.0')
          ##### from gi.repository import NM

    - name: "Configuring sshd (1/5)..."
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?Port [0-9]+$"
        replace: "Port {{ ssh_port }}"
        backup: no
      notify: Restart sshd

    - name: "Configuring sshd (2/5)..."
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?UseDNS .+$"
        replace: "UseDNS no"
        backup: no
      notify: Restart sshd

    - name: "Configuring sshd (3/5)..."
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin .+$"
        replace: "PermitRootLogin prohibit-password"
        backup: no
      notify: Restart sshd

    - name: "Configuring sshd (4/5)..."
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitEmptyPasswords .+$"
        replace: "PermitEmptyPasswords no"
        backup: no
      notify: Restart sshd

    - name: "Configuring sshd (5/5)..."
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^AllowUsers root@localhost root@127.0.0.1 {{ user }}@127.0.0.1 {{ user }}@localhost {{ user }}@{{ network_subnet | ipaddr('network') | regex_replace('\\.0$','.*') }} root@{{ network_subnet | ipaddr('network') | regex_replace('\\.0$','.*') }}"
        line: "AllowUsers root@localhost root@127.0.0.1 {{ user }}@127.0.0.1 {{ user }}@localhost {{ user }}@{{ network_subnet | ipaddr('network') | regex_replace('\\.0$','.*') }} root@{{ network_subnet | ipaddr('network') | regex_replace('\\.0$','.*') }}"
        backup: no
      notify: Restart sshd

    - name: "Configuring firewalld (1/3)..."
      copy:
        src: "{{ role_path }}/files/firewalld.xml"
        dest: /etc/firewalld/zones/public.xml
        mode: "0644"
        owner: "root"
        group: "root"
        force: no
      notify: Restart firewalld

    - name: "Configuring firewalld (2/3)..."
      replace:
        path: /etc/firewalld/zones/public.xml
        regexp: "private-network-ansible-template"
        replace: "{{ network_subnet }}"
        backup: no
      notify: Restart firewalld

    - name: "Configuring firewalld (3/3)..."
      replace:
        path: /etc/firewalld/zones/public.xml
        regexp: "ssh-port-ansible-template"
        replace: "{{ ssh_port | string }}"
        backup: no
      notify: Restart firewalld

    - name: "Disabling ufw..."
      systemd:
        name: "ufw"
        state: stopped
        enabled: no
      notify: Restart firewalld

    - name: "Configuring libvirt... (1/5)"
      copy:
        src: "{{ role_path }}/files/libvirt-network.xml"
        dest: /etc/libvirt/qemu/networks/default.xml
        mode: "0777"
        owner: libvirt-qemu
        group: libvirt-qemu
        force: no
      notify: Restart libvirtd

    - name: "Configuring libvirt... (2/5)"
      replace:
        path: /etc/libvirt/qemu/networks/default.xml
        regexp: private-network-net-ansible-template
        replace: "{{ network_subnet | ipaddr('1') | ipaddr('ip') }}" # A.B.C.0/24 -> A.B.C.1
        backup: no
      notify: Restart libvirtd

    - name: "Configuring libvirt... (3/5)"
      replace:
        path: /etc/libvirt/qemu/networks/default.xml
        regexp: private-network-mask-ansible-template
        replace: "{{ network_subnet | ipaddr('netmask') }}" # A.B.C.0/24 -> 255.255.255.0
        backup: no
      notify: Restart libvirtd

    - name: "Configuring libvirt... (4/5)"
      copy:
        src: "{{ role_path }}/files/libvirt-vm.xml"
        dest: "/etc/libvirt/qemu/{{ rdp_name }}.xml"
        mode: "0777"
        owner: libvirt-qemu
        group: libvirt-qemu
        force: no
      notify: Restart libvirtd

    - name: "Configuring libvirt... (5/5)"
      replace:
        path: "/etc/libvirt/qemu/{{ rdp_name }}.xml"
        regexp: rdp_name
        replace: "{{ rdp_name }}"
        backup: no
      notify: Restart libvirtd

    - name: "Configuring fs.inotify.max_user_watches for vscode..."
      lineinfile:
        path: /etc/sysctl.conf
        state: present
        regexp: ^fs.inotify.max_user_watches.*$
        line: "fs.inotify.max_user_watches = 524288"
        backup: no
      notify: Kernel attributes update

    - name: "Configuring dunst alternative notification service (1/4)..."
      file:
        path: /etc/dunst
        state: directory

    - name: "Configuring dunst alternative notification service (2/4)..."
      template:
        src: "{{ role_path }}/files/dunst.ini.tpl"
        dest: /etc/dunst/dunstrc
        mode: "0755"
        owner: "root"
        group: "root"

    - name: "Logical evaluation..."
      stat:
        path: /usr/share/dbus-1/services/org.gnome.Shell.Notifications.service
      register: f

    - name: "Configuring dunst alternative notification service (3/4)..."
      command: "mv /usr/share/dbus-1/services/org.gnome.Shell.Notifications.service /usr/share/dbus-1/services/org.gnome.Shell.Notifications.service.disabled"
      when: f.stat.exists

    - name: "Logical evaluation..."
      stat:
        path: /usr/share/dbus-1/services/com.ph-uhl.deadd.notification.service
      register: f

    - name: "Configuring dunst alternative notification service (4/4)..."
      command: "mv /usr/share/dbus-1/services/com.ph-uhl.deadd.notification.service /usr/share/dbus-1/services/com.ph-uhl.deadd.notification.service.disabled"
      when: f.stat.exists

    - name: "Configuring grub (1/2)..."
      lineinfile:
        path: /etc/default/grub
        state: present
        regexp: "^(GRUB_TIMEOUT=)([0-9]+)?$"
        line: "GRUB_TIMEOUT=0"
        backup: no
      notify: Update grub

    - name: "Configuring grub (2/2)..."
      lineinfile:
        path: /etc/default/grub
        state: present
        regexp: "^(GRUB_RECORDFAIL_TIMEOUT=)([0-9]+)?$"
        line: "GRUB_RECORDFAIL_TIMEOUT=0"
        backup: no
      notify: Update grub

    - name: "Logical evaluation..."
      stat:
        path: "/boot/efi/EFI/refind/refind.conf"
      register: f

    - name: "Logical evaluation..."
      set_fact:
        refindConfPath: "/boot/efi/EFI/BOOT/refind.conf"
      when: not f.stat.exists

    - name: "Logical evaluation..."
      set_fact:
        refindConfPath: "/boot/efi/EFI/refind/refind.conf"
      when: f.stat.exists

    - name: "Configuring Refind..."
      replace:
        path: "{{ refindConfPath }}"
        regexp: "^(timeout )([0-9]+)?$"
        replace: '\g<1>2'
        backup: no
      notify: Update grub

    - name: "Masking ctrl-alt-del.target..."
      systemd:
        name: "ctrl-alt-del.target"
        enabled: no
        masked: yes
        daemon_reload: yes

    - name: "Configuring motd..."
      copy:
        src: "{{ role_path }}/files/motd"
        dest: /etc/motd
        mode: "0755"
        owner: "root"
        group: "root"

    - name: "Preparing installation script context..."
      file:
        path: "/tmp/brprinter-installer.log"
        state: absent
      changed_when: false

    - name: "Preparing installation script context..."
      file:
        path: "/tmp/brprinter-installer.log"
        state: touch
        mode: "0777"
        owner: "root"
      changed_when: false

    - name: "Preparing installation script context..."
      copy:
        src: "{{ role_path }}/files/brprinter-installer.sh"
        dest: /tmp/brprinter-installer.sh
        mode: "0755"
        owner: "root"
        group: "root"
        force: no
      changed_when: false

    - name: "Installing Printer..."
      shell: echo -e "{{ printer_model }}\n1\n{{ printer_ip }}" | /bin/bash "/tmp/brprinter-installer.sh"
      args:
        chdir: "/tmp/"
      register: printer
      changed_when: "'Creation du dossier ' in printer.stdout"
      notify: Fix broken packages

    - name: "Logical evaluation..."
      shell: /usr/bin/lpstat -d | grep "{{ printer_model }}" | cat
      register: defaultPrinter
      changed_when: false

    - name: "Set default printer..."
      shell: /usr/sbin/lpadmin -d "{{ printer_model }}"
      when: defaultPrinter.stdout | length == 0

    - name: "Cleaning artefacts..."
      file:
        state: absent
        path: "/tmp/packages/"
      changed_when: false

    # - name: "Configuring fstab... (1/5)"
    #   mount:
    #     path: /Cloud
    #     src: UUID=9412512e-6067-4c71-af92-167a429bea55
    #     fstype: ext4
    #     opts: defaults
    #     state: mounted

    # - name: "Configuring fstab... (2/5)"
    #   mount:
    #     path: /VMs
    #     src: UUID=98e934a0-fe74-4cc4-b2d8-2b3346e035a6
    #     fstype: ext4
    #     opts: defaults
    #     state: mounted

    # - name: "Configuring fstab... (3/5)"
    #   mount:
    #     path: /Jeux
    #     src: UUID=06043a2d-b9e3-4775-8373-e10d832a6914
    #     fstype: ext4
    #     opts: defaults
    #     state: mounted

    # - name: "Configuring fstab... (4/5)"
    #   mount:
    #     path: /Films
    #     src: UUID=18B2EA1DB2E9FF5E
    #     fstype: ntfs-3g
    #     opts: rw,auto,gid=100,uid=1000,nls=utf8,umask=002
    #     state: mounted

    # - name: "Configuring fstab... (5/5)"
    #   mount:
    #     path: /Musique
    #     src: UUID=14D00075D0005F7C
    #     fstype: ntfs-3g
    #     opts: rw,auto,gid=100,uid=1000,nls=utf8,umask=002
    #     state: mounted

    - name: "Preparing SSH for root user..."
      file:
        path: /root/.ssh/
        state: directory
        mode: "0755"
        owner: "root"
        group: "root"

    - name: "Generating SSH key pair for root user..."
      openssh_keypair:
        path: /root/.ssh/id_rsa
        size: 4096
        type: rsa

    # - name: "Set authorized key for user root..."
    #   authorized_key:
    #     user: root
    #     state: present
    #     key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    #     ## suspected to be run locally...

    - name: "Checking known_hosts..."
      stat:
        path: "/root/.ssh/known_hosts"
      register: p

    - name: "Set known_hosts for user root..."
      shell: ssh-keyscan -p "{{ ssh_port }}" -H localhost >> "/root/.ssh/known_hosts"
      when: p.stat.exists == False

    - name: "Configuring aliases (1/2)..."
      template:
        src: "{{ role_path }}/files/bash_aliases.tpl"
        dest: "{{ line_item.home }}/.bash_aliases"
        mode: "0755"
        owner: "{{ line_item.user }}"
        group: "{{ line_item.user }}"
        variable_start_string: "[%" # because script contains default character
        variable_end_string: "%]" # because script contains default character
        comment_start_string: "{=" # because script contains default character
        comment_end_string: "=}" # because script contains default character
      with_items:
        - { home: "/root", user: "root" }
        - { home: "{{ home }}", user: "{{ user }}" }
      loop_control:
        loop_var: line_item

    - name: "Configuring aliases (2/2)..."
      lineinfile:
        path: "{{ home_item }}/.bashrc"
        state: present
        regexp: ^(\s*)(.|source)( ~/.bash_aliases)(\s*)$
        line: ". ~/.bash_aliases"
        backup: no
      with_items:
        - /root
        - "{{ home }}"
      loop_control:
        loop_var: home_item

    - name: "Check if {{ user }} exists"
      getent:
        database: passwd
        # key: "user"
        key: "{{ user }}"
        fail_key: False
      register: userExists

    - name: "Check if {{ user }} has ssh key"
      stat:
        path: "{{ home }}/.ssh/id_rsa"
      register: userHasSshKey

    - name: "Creating {{ user }} user with SSH key..."
      user:
        name: "{{ user }}"
        comment: "{{ user }}"
        group: "{{ user }}"
        shell: /bin/bash
        createhome: yes # create_home since Ansible 2.5
        password: "{{ password | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_file: "{{ home }}/.ssh/id_rsa"
        ssh_key_bits: 4096
        ssh_key_type: rsa
      when: user not in userExists.ansible_facts.getent_passwd or not userHasSshKey.stat.exists

    - name: "Finding Mouse Vendor ID..."
      shell: lsusb | awk 'tolower($0) ~ /mouse/ {gsub(":[0-9a-f]+", "",$6); print $6; exit}'
      register: command_output
      changed_when: false

    - name: Logical evaluation...
      set_fact:
        mouse_vendor: "{{ command_output.stdout }}"
        changed_when: false

    - name: "Configuring no-wakup-from-mouse udev rule..."
      template:
        src: "{{ role_path }}/files/no-wakup-from-mouse.rules.tpl"
        dest: /etc/udev/rules.d/98-no-wakup-from-mouse.rules
        mode: "0644"
        owner: "root"
        group: "root"
        force: yes
      notify:
        - Reload udev rules 1
        - Reload udev rules 2

    # - name: "Configuring wayland as window manager..."
    #   lineinfile:
    #     path: /etc/gdm3/custom.conf
    #     state: present
    #     line: "WaylandEnable=true"
    #     backup: no

  environment:
    PWD: ""

  become: yes
  become_user: "root"

- block:
    - name: "Configuring dunst alternative notification service..."
      file:
        src: /etc/dunst
        dest: "{{ home }}/.config/dunst"
        state: link

    - name: "Starting dunst alternative notification service..."
      systemd:
        name: dunst
        state: started
        enabled: yes
        scope: user
        daemon_reload: true

    - name: "Fix owner of the generated pub key"
      file:
        path: "{{ home }}/.ssh/id_rsa.pub"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0777"
      changed_when: false # to be checked

    - name: "Fix owner of the generated priv key"
      file:
        path: "{{ home }}/.ssh/id_rsa"
        owner: "{{ user }}"
        group: "{{ user }}"

    # - name: "Set authorized key for user {{ user }}..."
    #   authorized_key:
    #     user: "{{ user }}"
    #     state: present
    #     key: "{{ lookup('file', '{{ home }}/.ssh/id_rsa.pub') }}"
    #     ## suspected to be run locally...

    - name: "Fix owner of the generated pub key 2"
      file:
        path: "{{ home }}/.ssh/id_rsa.pub"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
      changed_when: false # to be checked

    - name: "Checking known_hosts..."
      stat:
        path: "{{ home }}/.ssh/known_hosts"
      register: p

    - name: "Set known_hosts for user {{ user }}..."
      shell: ssh-keyscan -p "{{ ssh_port }}" -H localhost >> "{{ home }}/.ssh/known_hosts"
      when: p.stat.exists == False

  become: yes
  become_user: "{{ user }}"
  environment:
    PWD: ""
